# Generated by Django 6.0.4 on 2026-05-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_atsscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atsscore',
            name='created_at',
        ),
        migrations.AddField(
            model_name='atsscore',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
