# Generated by Django 6.0.4 on 2026-06-04 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_aiinterviewsession_aiquestion_aianswer_calllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('intro', 'Introduction'), ('experience', 'Experience'), (
                    'skills', 'Skills'), ('availability', 'Availability'), ('salary', 'Salary')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question_index', models.IntegerField(default=0)),
                ('session', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='jobs.aiinterviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='JobQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('question', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='jobs.questiontemplate')),
            ],
        ),
    ]
