# Generated by Django 6.0.4 on 2026-06-23 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_paymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(
                    decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='jobs.paymenttransaction')),
            ],
        ),
    ]
