# Generated by Django 6.0.4 on 2026-04-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_candidateprofile_employerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='resume',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='education',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(default='Beginner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='domain',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
    ]
