# Generated by Django 6.0.4 on 2026-04-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_candidateprofile_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, null=True,
                                   upload_to='resumes/'),
        ),
    ]
